name: MinecraftServerPassword
version: '${version}'
main: host.hunters.minecraftserverpassword.MinecraftServerPassword
api-version: 1.19
authors: [hunterwebbs, insyri]

commands:
  setpassword:
    description: Set the password for the server.
    usage: "Usage: /<command> [password]"
    aliases: [setpass, sp]
    permission:
      serverpassword.admin

  whitelistadd:
    description: Manually add a user to the whitelist.
    usage: "Usage: /<command> [username]"
    aliases: [wladd]
    permission:
      serverpassword.admin
